### ISSUE TITLE
Bug mobile browsers

### ISSUE THREAD

**Issue by panzerank** [backdrop-contrib/axioma#9]
The top menu writings are not visible with Safari, Mozilla, Chrome and iPhone browsers.
Thank you

**Comment by korontari** [comment]
@panzerank , thank you for reporting this! Looks like the issue appeared after the latest Backdrop update. I am looking into it.

**Comment by korontari** [comment]
It looks like [changes in menu settings](https://github.com/backdrop/backdrop-issues/issues/6264) broke the display of the theme's menu. I am going to implement these changes in the theme, but for now I got a hot fix in order to make mobile menu work again. @panzerank , could you please test the #10 PR and let me know if it works for you? Especially for iPhone browsers as I only have emulators for these to test.
